### ISSUE TITLE
Tab size inconsistency

### ISSUE THREAD

**Issue by henrywright** [GoogleChrome/text-app#261]
Hey guys!

Setting the tab size to 4 allows me to press the tab key and have the cursor indent 4 spaces. That's great. However, if I highlight an unindented block of text and press `Ctrl + {` together so that the block becomes indented, I noticed the indent is just 2 spaces instead of the expected 4.

**Comment by beaufortfrancois** [comment]
Hello Henry,
Thanks for your feedback.

I've just submitted a Pull Request at https://github.com/GoogleChrome/text-app/pull/262 which will fix this issue.

**Comment by beaufortfrancois** [comment]
And it's now live at https://chrome.google.com/webstore/detail/text/mmfbcljfglbokpmkimbfghdkjmjhdgbg/reviews
Please reopen the issue if that's not working as intended.

**Comment by henrywright** [comment]
@beaufortfrancois I just tested at my end. Works great. Thank you
