### ISSUE TITLE
Block tabbing content results in spaces being used instead of tabs

### ISSUE THREAD

**Issue by henrywright** [GoogleChrome/text-app#264]
If I select a block of text and then hit the tab key on my keyboard, the block of text is indented using spaces instead of tabs.

**Comment by beaufortfrancois** [comment]
You're right. See https://github.com/GoogleChrome/text-app/blob/8e2e4bbd25f91a370d3078e37235467f2a21e50a/js/editor-cm.js#L194
Let me see what I can do.

**Comment by beaufortfrancois** [comment]
It has been accepted!

**Comment by henrywright** [comment]
Excellent! Thank you :)

**Comment by henrywright** [comment]
Sorry for the newbie question; I'm using Text as a Chromium app, will I need to update before I can use the enhancement?

**Comment by beaufortfrancois** [comment]
I will bump app version and update the chrome webstore item.
Then you will automatically get the new version with the fix.

**Comment by henrywright** [comment]
OK great. Thanks again!
