### ISSUE TITLE
Block tabbing text deletes the text instead of indenting it

### ISSUE THREAD

**Issue by henrywright** [GoogleChrome/text-app#267]
Hi guys,

This issue could be related to the changes that were made in [#264](https://github.com/GoogleChrome/text-app/issues/264), I'm not sure.

When I select a block of text and press the tab key on my keyboard, the block of text is deleted. I'd expect the block of text to remain on the page and be indented by one _tab_.

**Comment by beaufortfrancois** [comment]
If "Tabs to spaces" setting is checked, it should not delete text.
Can you confirm?

**Comment by henrywright** [comment]
When 'Tabs to spaces' is checked, the text I've highlighted isn't deleted when I block tab it. It gets indented _by spaces_.

**Comment by beaufortfrancois** [comment]
Will have a look this week I promise! Sorry for the late response.

**Comment by henrywright** [comment]
Cool! Thanks :)

**Comment by beaufortfrancois** [comment]
I'm waiting for review.
Once this is approved, I'll push an update to the Text App.

**Comment by beaufortfrancois** [comment]
I've just updated the Text App to Chrome Web Store: https://chrome.google.com/webstore/detail/mmfbcljfglbokpmkimbfghdkjmjhdgbg
Please reopen this issue if you're still experiencing original behaviour. 

Thank you again for reporting this!

**Comment by henrywright** [comment]
Thanks @beaufortfrancois!
