### ISSUE TITLE
Typing does not continue until click.

### ISSUE THREAD

**Issue by DizzyZane** [GoogleChrome/text-app#268]
Loved it until now, however all of a sudden, for some reason when alt-tabbing back to it, it doesn't continue to let me type until I click, which is really annoying and destroys many minutes of work. Please either fix or offer a workaround.

**Comment by beaufortfrancois** [comment]
Thank you for reporting this issue.

I sadly cannot reproduce the issue. Can you give specific workflow?
Which version of Chrome (Chrome OS) are you running?

**Comment by DizzyZane** [comment]
Latest, seems to have fixed itself today. I'm going to close + comment. Thank you!
